import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.rightmove.co.uk/');
  await page.getByTestId('typeahead-searchbox').click();
  await page.getByTestId('typeahead-searchbox').fill('manchester');
  await page.getByRole('button', { name: 'Manchester, Greater Manchester', exact: true }).click();
  await page.getByTestId('forSaleCta').click();
  await page.getByLabel('Search radius').selectOption('20.0');
  await page.getByTestId('propertyTypes').selectOption('20.0');
  await page.getByTestId('propertyTypes').selectOption('bungalow');
  await page.getByTestId('minPrice').selectOption('140000');
  await page.getByTestId('minPrice').selectOption('140000');
  await page.getByTestId('minPrice').selectOption('140000');
  await page.getByTestId('minPrice').selectOption('140000');
  await page.getByTestId('minPrice').selectOption('140000');
  await page.getByTestId('minPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByTestId('maxPrice').selectOption('140000');
  await page.getByLabel('Added to site').selectOption('140000');
  await page.getByRole('button', { name: 'Search properties' }).click();
  await page.getByTestId('propertyCard-1').getByTestId('image-swiper-container').getByRole('link', { name: 'Link to property details page' }).click();
});